# Generated by Django 6.0.5 on 2026-05-31 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('domain', models.URLField(blank=True, max_length=500)),
                ('industry', models.CharField(choices=[('tech', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('retail', 'Retail'), ('manufacturing', 'Manufacturing'), ('energy', 'Energy'), ('media', 'Media & Entertainment'), ('education', 'Education'), ('real_estate', 'Real Estate'), ('other', 'Other')], default='tech', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True, max_length=500)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('headquarters', models.CharField(blank=True, max_length=255)),
                ('employee_count', models.CharField(blank=True, max_length=50)),
                ('revenue_range', models.CharField(blank=True, max_length=100)),
                ('is_competitor', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracked_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('product_launch', 'Product Launch'), ('pricing_change', 'Pricing Change'), ('hiring', 'Hiring Activity'), ('partnership', 'Partnership'), ('funding', 'Funding Round'), ('acquisition', 'Acquisition'), ('expansion', 'Market Expansion'), ('leadership', 'Leadership Change'), ('technology', 'Technology Adoption'), ('marketing', 'Marketing Campaign'), ('legal', 'Legal/Regulatory'), ('news', 'General News')], default='news', max_length=50)),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=20)),
                ('impact', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('confidence_score', models.FloatField(default=0.5, help_text='0-1 confidence in data accuracy')),
                ('is_verified', models.BooleanField(default=False)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='api.company')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('pattern_type', models.CharField(choices=[('trend', 'Trend'), ('cycle', 'Cycle'), ('anomaly', 'Anomaly'), ('correlation', 'Correlation'), ('strategy_shift', 'Strategy Shift')], default='trend', max_length=50)),
                ('confidence', models.FloatField(default=0.5, help_text='0-1 confidence score')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='api.company')),
                ('supporting_data', models.ManyToManyField(blank=True, related_name='patterns', to='api.datapoint')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('recommendation', models.TextField(blank=True, help_text='Suggested action to take')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('acted_on', 'Acted On'), ('dismissed', 'Dismissed')], default='new', max_length=20)),
                ('predicted_timeline', models.CharField(blank=True, help_text='e.g., "Within 30 days"', max_length=100)),
                ('probability', models.FloatField(default=0.5, help_text='0-1 probability of prediction')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='api.company')),
                ('related_patterns', models.ManyToManyField(blank=True, related_name='insights', to='api.pattern')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spider_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('items_scraped', models.IntegerField(default=0)),
                ('errors', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_jobs', to='api.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overlap_score', models.FloatField(default=0.0, help_text='0-100 score of competitive overlap')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_relationships', to='api.company')),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competing_with', to='api.company')),
            ],
            options={
                'unique_together': {('company', 'competitor')},
            },
        ),
        migrations.AddIndex(
            model_name='datapoint',
            index=models.Index(fields=['company', 'category'], name='api_datapoi_company_131f63_idx'),
        ),
        migrations.AddIndex(
            model_name='datapoint',
            index=models.Index(fields=['company', 'published_at'], name='api_datapoi_company_b1746e_idx'),
        ),
    ]
