# Generated by Django 6.0.5 on 2026-06-08 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='category',
            field=models.CharField(choices=[('product_launch', 'Product Launch'), ('pricing_change', 'Pricing Change'), ('hiring', 'Hiring Activity'), ('partnership', 'Partnership'), ('funding', 'Funding Round'), ('acquisition', 'Acquisition'), ('expansion', 'Market Expansion'), ('leadership', 'Leadership Change'), ('technology', 'Technology Adoption'), ('marketing', 'Marketing Campaign'), ('legal', 'Legal/Regulatory'), ('patent', 'Patent Filing'), ('earnings', 'Earnings/Financial'), ('news', 'General News')], default='news', max_length=50),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='pattern_type',
            field=models.CharField(choices=[('trend', 'Trend'), ('cycle', 'Cycle'), ('anomaly', 'Anomaly'), ('correlation', 'Correlation'), ('strategy_shift', 'Strategy Shift'), ('velocity_alert', 'Velocity Alert'), ('compound', 'Compound Signal'), ('pre_launch', 'Pre-Launch Pattern')], default='trend', max_length=50),
        ),
        migrations.CreateModel(
            name='Battlecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('recent_moves', models.JSONField(default=list, help_text='Last 5 strategic moves')),
                ('pricing_position', models.CharField(blank=True, help_text='premium/mid/budget', max_length=50)),
                ('target_market', models.CharField(blank=True, max_length=200)),
                ('key_differentiators', models.JSONField(default=list)),
                ('win_themes', models.JSONField(default=list, help_text='Why customers choose them')),
                ('loss_themes', models.JSONField(default=list, help_text='Why customers leave them')),
                ('objection_handlers', models.JSONField(default=list)),
                ('current_trajectory', models.CharField(blank=True, help_text='growing/stable/declining', max_length=50)),
                ('threat_assessment', models.TextField(blank=True)),
                ('signal_summary', models.TextField(blank=True, help_text='Auto-generated from latest signals')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('auto_update_count', models.IntegerField(default=0)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='battlecard', to='api.company')),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='DeadReckoning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_headcount', models.IntegerField(default=0)),
                ('current_arr', models.FloatField(default=0, help_text='Estimated ARR in millions')),
                ('current_market_share', models.FloatField(default=0, help_text='Estimated market share %')),
                ('current_product_count', models.IntegerField(default=0)),
                ('current_geo_markets', models.IntegerField(default=1)),
                ('hiring_velocity', models.FloatField(default=0, help_text='Jobs per month')),
                ('product_velocity', models.FloatField(default=0, help_text='Launches per quarter')),
                ('funding_total', models.FloatField(default=0, help_text='Total known funding in millions')),
                ('expansion_velocity', models.FloatField(default=0, help_text='New markets per year')),
                ('projected_headcount_6m', models.IntegerField(default=0)),
                ('projected_headcount_12m', models.IntegerField(default=0)),
                ('projected_arr_6m', models.FloatField(default=0)),
                ('projected_arr_12m', models.FloatField(default=0)),
                ('projected_products_6m', models.IntegerField(default=0)),
                ('projected_products_12m', models.IntegerField(default=0)),
                ('projected_markets_6m', models.IntegerField(default=0)),
                ('projected_markets_12m', models.IntegerField(default=0)),
                ('confidence', models.FloatField(default=0.5)),
                ('projection_narrative', models.TextField(blank=True, help_text='Plain language projection')),
                ('key_assumptions', models.JSONField(default=list)),
                ('risk_factors', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dead_reckonings', to='api.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('content_text', models.TextField(help_text='Cleaned text of pricing page')),
                ('content_html', models.TextField(blank=True, help_text='Raw HTML')),
                ('content_hash', models.CharField(help_text='SHA256 hash for change detection', max_length=64)),
                ('has_changed', models.BooleanField(default=False)),
                ('diff_from_previous', models.TextField(blank=True, help_text='Diff from previous snapshot')),
                ('plan_names', models.JSONField(blank=True, default=list)),
                ('prices', models.JSONField(blank=True, default=list)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_snapshots', to='api.company')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('job_posting', 'Job Posting'), ('patent_filing', 'Patent Filing'), ('pricing_change', 'Pricing Page Change'), ('earnings_keyword', 'Earnings Call Keyword'), ('leadership_change', 'Leadership Change'), ('funding_event', 'Funding Event'), ('product_signal', 'Product Signal')], max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('role_type', models.CharField(blank=True, help_text='e.g., Engineering, Sales, Marketing', max_length=100)),
                ('seniority_level', models.CharField(blank=True, help_text='e.g., VP, Director, Senior, Entry', max_length=50)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('patent_category', models.CharField(blank=True, max_length=200)),
                ('patent_id', models.CharField(blank=True, max_length=100)),
                ('keyword', models.CharField(blank=True, max_length=100)),
                ('keyword_count', models.IntegerField(default=0)),
                ('quarter', models.CharField(blank=True, help_text='e.g., Q1 2025', max_length=10)),
                ('diff_summary', models.TextField(blank=True)),
                ('old_snapshot', models.TextField(blank=True)),
                ('new_snapshot', models.TextField(blank=True)),
                ('strength', models.FloatField(default=0.5, help_text='0-1 signal strength')),
                ('velocity', models.FloatField(default=0.0, help_text='Rate of change')),
                ('anomaly_score', models.FloatField(default=0.0, help_text='How far from baseline')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='api.company')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='CompoundSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('hypothesis', models.TextField(help_text='Strategic intent inference in plain language')),
                ('signal_count', models.IntegerField(default=0)),
                ('confidence', models.FloatField(default=0.5, help_text='Confidence based on independent signal count')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('time_window_days', models.IntegerField(default=30, help_text='Window within which signals co-occurred')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compound_signals', to='api.company')),
                ('contributing_datapoints', models.ManyToManyField(blank=True, related_name='compound_signals', to='api.datapoint')),
                ('contributing_signals', models.ManyToManyField(related_name='compound_signals', to='api.signal')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['company', 'signal_type'], name='api_signal_company_fef97d_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['company', 'captured_at'], name='api_signal_company_e9e876_idx'),
        ),
    ]
